### ISSUE TITLE
Conflict with standard in nested ternary expression

### ISSUE THREAD

**Issue by aMarCruz** [brodybits/prettierx#44]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wDMII8BePUgVyjBgEto8AKbAGj2aIGUMAQzBwAlHmAAdKHgLQSeGAE8McangD0AdxwBrAD4xsQgEZCAVhANwAthmxwiQg1DgBzCGFabmAOngSTj8AFVVxGTk5AH48AHIYOMiopC0ACwhbOAMM9yFsAwAFOGwiaCEAGyL8ljA6CvyDMCFnXwCnGGCwtTFkqLxYuKTZfrxUqHqKmWTHGDpsWRU1GQBfGRAuEAgMFgVkUHzsCG1C-IQiZBAhADcIZgATDZBTEzA9OBhBEWYod2RjOhwTZpGC2CoAdTSzECwlE-HO0OY12hykuYCIF02PyIJRghRM7lsQmQpEqOM2FiIaAAQq93p8hFkADI-OAkslAkCUtD8H7uCpwACKdAg8HZFXJIGEpRKl3MpmUFWgTwcPxg4IeMDSyAAHAAGTYOCA48EmDCXBxOErXNmbRwARzozEc+KEhOJSFJEs5ONszH+2EBmyIfIFwtFbM9HM2MDMGvuWuQACYYyZmBU+QBhTJEy5QaC2kB0HEhMwXKPelYrIA)
```sh
--parser babylon
```

**Input:**
```jsx
export const foo = function (r, isSpace) {
  const type = /work|trabajo|empresa|negocio/i.test(r.Type)
    ? 't'
    : /home|hogar|Personal|Particular|casa/i.test(r.Type)
      ? ''
      : null

  return type
}

```

**Output:**
```jsx
export const foo = function(r, isSpace) {
  const type = /work|trabajo|empresa|negocio/i.test(r.Type)
    ? "t"
    : /home|hogar|Personal|Particular|casa/i.test(r.Type)
    ? ""
    : null;

  return type;
};

```

**Expected behavior:**

The **Input** must be preserved.

The ESLint `indent` rule for StandardJS has `flatTernaryExpressions: true`, as seen in [enforce consistent indentation (indent)](https://eslint.org/docs/rules/indent).

@brodybits , thanks for your awesome fork!

**Comment by brody2consult** [comment]
Thanks @aMarCruz for reporting.

I think `prettier` used to be consistent with `standard`, they changed it in prettier/prettier#5039 (some more info in prettier/prettier#5476; original discussion was in prettier#737).

There is already some discussion in prettier/prettier#5814 to bring the nested indentation back as an option. If they do this, it would be easiest to merge it in.

And thanks for the kind words!

P.S. The rationale seems to have been consistency with if/else formatting style, especially interesting for JSX. Nice example in <https://github.com/prettier/prettier/issues/737#issuecomment-293183304>:

> ```js
> const StorybookLoader = ({ match }) => (
>   match.params.storyId === "button"
>     ? <ButtonStorybook />
>     : match.params.storyId === "color"
>     ? <ColorBook />
>     : match.params.storyId === "typography"
>     ? <TypographyBook />
>     : match.params.storyId === "loading"
>     ? <LoaderStorybook />
>     : match.params.storyId === "deal-list"
>     ? <DealListStory />
>     : (
>       <Message>
>         <Title>{'Missing story book'}</Title>
>         <Content>
>           <BackButton/>
>         </Content>
>       </Message>
>     )
> )
> ```

**Comment by aMarCruz** [comment]
@brodybits seems good, thanks. I like the Prettier format on this :)

PS: The only drawback is the inability of ESLint to accept that format :(

**Comment by brody2consult** [comment]
> PS: The only drawback is the inability of ESLint to accept that format :(

Yes, and I would like to find a way to resolve the inconsistency if possible. I would like to keep this one open as an enhancement.

Someone mentioned an interesting alternative in <https://github.com/prettier/prettier/issues/5814#issuecomment-460303495>:

> I'm actually considering something similar to what we do for JSX, though I'm not sure about it:
> 
> ```js
> const result = type === 'first' ? (
>   getFirstThing()
> ) : type === 'second' ? (
>   getSecondThing()
> ) : (
>   getOtherThing()
> )
> ```

I think this form would be a little bit more consistent with using if as an expression, which is supported in some languages including CoffeeScript. Interesting discussion in: <https://stackoverflow.com/questions/44770962/difference-between-if-as-an-expression-and-if-as-a-statement>

**Comment by aMarCruz** [comment]
Good, using parentheses works well with the "indent" rule and auto-indent in vs code.

**Comment by brody2consult** [comment]
> using parentheses works well with the "indent" rule and auto-indent in vs code.

Unfortunately, I think Prettier will remove the parens and flatten the nested ternary - see this [playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAnOaCuANlgLyYwCeADnJifZgOQBmAltho5gPyYAUAHSiZMAczgwAYuwwAVABasoovgEohqzEnLVa9MozRxIUACZdeg4WIkBlY9FMKlK9VE3arI8TADyMeThsZ2U1DRAAGhAIKhhWdGRQAENsbAgAdwAFFIQ0ZBAkgDcIVlNIkAAjbCSwAGs7KhqXZBhsfDgo+RgAW0IAdUV4NEawOHsoNFY4wqmKfLA0PKilI2wYTOrRbqTkZiTCIyiAKzQADwAharq7JO64ABklOF39w5AT09sXQjgARXwIPAXgcOiBGhwgvkKkkKhRCNBylRsEoYH1SgFkAAOAAMUSRECMfWqVHySLwQUKzyiuAAjvh2HANkktjskHsQVEjN1WC02qDJsofv9Ac82a9QTAYWjTBikAAmKKtJKsQguADCEG623yUGgVJA+CMshheTFIIAvuagA)

So we would probably want an option such as "ternaries with parens" or "nested ternaries with parens". It would be ideal if we could get this kind of an option on Prettier itself, in response to <https://github.com/prettier/prettier/issues/5814#issuecomment-460303495>.

**Comment by aMarCruz** [comment]
he, another undesired effect (TypeScript):

```ts
type TypeName<T> = T extends string ? 'string'
  : T extends number ? 'number'
  : T extends boolean ? 'boolean'
  : T extends undefined ? 'undefined'
  : T extends Function ? 'function'
  : 'object'
```

after prettier:

```ts
type TypeName<T> = T extends string
  ? 'string'
  : T extends number
  ? 'number'
  : T extends boolean
  ? 'boolean'
  : T extends undefined
  ? 'undefined'
  : T extends Function
  ? 'function'
  : 'object'
```

**Comment by brody2consult** [comment]
> he, another undesired effect (TypeScript):
> [...]

Argh thanks, just added the **bug** label again.

I think we should bring back the nested indentation as an option, as discussed earlier in this issue.

**Comment by aMarCruz** [comment]
@brodybits yes, or an option to disable it.

btw: Seems ternary is a super-complex thing, ESLint [has a bug](https://github.com/eslint/eslint/issues/11397) in the `flatTernaryExpressions:true` of the 'indent' rule that complicates the integration.

**Comment by brody2consult** [comment]
This issue leads to sheerun/prettier-standard#76, hope to resolve it soon (no promises)

**Comment by aMarCruz** [comment]
@brodybits ,
In a few minutes, I will send you a PR that (almost) matches the behavior of `alignTernaryLines` to that of ESLint indent rule.

The most important thing is that ESLint, and so standard, _always_ indents the ternaries with the indentation set by the user. Prettier always indents them with 2 spaces. It seems that the current implementation of `alignTernaryLines` is incomplete, and although this new behavior is a breaking change, I do not think it is advisable to create a new option.

The change in src/language-js/printer-estree.js is minimal (4 or 5 lines). I corrected the snapshots of tests/ternaries, added others in tests/standard and retouched its spec. I also made a small change in the Readme and nothing more (no builds).

Today I will finish a plugin for eslint+prettierx (with presets for Standard and Prettierx) that can be used with the VS-Code ESLint extension.
In the https://github.com/aMarCruz/prettier-standard-test.git I explain the reasons and there are some tests using my local repo of the fork of prettierx.

My experience with prettier and Jest is minimal and maybe I did something wrong, but I hope you will review it. Thanks.

**Comment by brody2consult** [comment]
> Today I will finish a plugin for eslint+prettierx (with presets for Standard and Prettierx) that can be used with the VS-Code ESLint extension.

I will add a pointer if you publish it.

**Comment by aMarCruz** [comment]
@brodybits hi, the plugin is ready for testing: [eslint-plugin-prettierx](https://www.npmjs.com/package/eslint-plugin-prettierx).

I am using it since yesterday in my current project and it seems to work without problems.
Right now I'm testing it with [eslint-config-standardized](https://www.npmjs.com/package/eslint-config-standardize) that is my personal config.

Maybe when I have the time will try to use prettierx as a postproccesor or with a custom parser to solve some issues related to ASI, comment directives, and other things (or send a PR to Prettier to fix these).

**Comment by brody2consult** [comment]
Thanks @aMarCruz, I just added the links to README.md.

It looks like really nice work in general, I will need some time to take a deeper look. A couple questions so far:
- How would someone configure which preset to use in `eslint-plugin-prettierx`?
- In `eslint-config-standardize` what does "standardize" mean? (I found a `standardize` package on npm, not sure if it is related or not.)

**Comment by aMarCruz** [comment]
@brodybits thanks for your time.
I think I should make the documentation clearer. The plugin handles the `Program` (root) node, format the document and issue error messages to ESLint with the differences found. From there ESLint takes care of the rest.

The chosen preset configures the `prettierx/options` rule and clears conflicting ESLint rules. This rules are the same for any preset, the difference is the initial prettierx settings that you can override through `prettierx/options`, .prettierrc, or .editorconfig. So simply use the "eslint: recommended" preset (optional), then the prietterx preset and finally the rules to overwrite:

```js
{
  extends: [
    'eslint:recommended',
    'plugin:prettierx/default',  // <-- preset with prettierx defaults
  ],
  rules: {
    'no-callback-return': 'error',
    'prettierx/options': ['error', {
      'tabWidth': 4
    }]
  }
}
```

'eslint-config-standardize' is my personal config, the name because it is based in StandardJS. It has some few changes like "es5" trailing commas, double-quotes in JSX properties, etc. and more strict.

For other plugins, rules that conflict with prettierx should be avoided. All in a similar way to how it is done with the plugin and the "official" Prietter config. See [eslint-config-prettier](https://www.npmjs.com/package/eslint-config-prettier) and [eslint-plugin-prettier](https://www.npmjs.com/package/eslint-plugin-prettier).

If I see that there is enough interest I will rewrite the Readme to recommend eslint-config-prietter with instructions on how to use it.
